const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/css/retrodos.css'),'utf8');
const app=fs.readFileSync(path.join(root,'assets/js/app.js'),'utf8');
test('V3 shell exposes desktop and mobile navigation',()=>{for(const id of ['desktopRail','mobileMenu','heroMachineArt','featuredRail','gameList'])assert.match(html,new RegExp(`id="${id}"`))});
test('V3 player exposes touch command deck',()=>{for(const id of ['touchDeck','touchKeyboard','touchStatus','keyboardToggle','gameModeButton','focusGameButton','fullscreenButton'])assert.match(html,new RegExp(`id="${id}"`));for(const key of ['Escape','Enter','Space','Control','Alt','Shift','ArrowLeft','ArrowRight'])assert.match(html,new RegExp(`data-key="${key}"`))});
test('V2 fake CSS computer is removed',()=>{assert.doesNotMatch(html,/hero-computer/);assert.doesNotMatch(html,/class="computer"/);assert.doesNotMatch(css,/\.hero-computer\b/);assert.doesNotMatch(css,/\.computer\s*\{/)});
test('V3 has green and amber theme hooks',()=>{assert.match(html,/data-theme="green"/);assert.match(css,/body\[data-theme="amber"\]/);assert.match(app,/retrodos:theme:v3/)});
test('player keeps Internet Archive embed helper and best-effort touch message',()=>{assert.match(app,/buildArchiveEmbedUrl/);assert.match(app,/postMessage\(\{source:'retrodos',type:'virtual-key',key\}/);assert.match(html,/Archive peut ignorer certaines touches/)});
